# Generated by Django 3.2 on 2021-04-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_student_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
    ]
